Allow paginated_name customization
tfranzel/drf-spectacular pull request #488
Opened 2021-08-27 21:18 UTC by georgy-komarov

This PR allows to customize template name for paginated responses without overriding large amount of code in `AutoSchema._get_response_for_code` function

2021-08-28 14:27 UTC, tfranzel commented
hi! this is interesting. how would you customize that string for your purposes? is the `Paginated...` name not fitting or are you translating the names? usually i try to understand the motivation behind changes.

2021-10-03 17:15 UTC, georgy-komarov commented
Assuming having these serializers
```python
class CourseListItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = Course
        fields = (id', 'title')


class CourseViewItemSerializer(CourseListItemSerializer):
    class Meta(CourseListItemSerializer.Meta):
        fields = CourseListItemSerializer.Meta.fields + ('some_extra_field',)

    ...

class CourseSerializer(serializers.ModelSerializer):
    class Meta:
        fields = '__all__'

    ...
```
I use different serializers for list, retrieve and create/update. probably it is not the best variant possible but I find it pretty easy to understand and maintain.

In my specific case everything is about the serializer's naming
What i get is
`CourseListItemSerializer` -> `PaginatedCourseListItemList` (this one looks really werid)
`CourseViewItemSerializer` -> `PaginatedCourseViewItemList`

What I want to is to have
`CourseListItemSerializer` -> `PaginatedCourseListItems` (this one looks really werid)
`CourseViewItemSerializer` -> `PaginatedCourseViewItems`

However, as you already mentioned, this may be useful for translations.
And, all in all, magic strings should be customizable.

2021-10-03 17:25 UTC, tfranzel requested changes
I see. yes makes total sense. just wanted to understand the motivation. let's make this public with `get_paginated_name`. 

if you do it right away, it will be part of the next release today.

2021-10-03 17:34 UTC, tfranzel approved these changes

2021-10-03 17:34 UTC, merged