fix jwt cookie name settings not being recognised
tfranzel/drf-spectacular pull request #972
Opened 2023-04-05 05:31 UTC by nixsiow

This should fix the issue by getting the cookie_name from the dj_rest_auth.app_settings instead of Django settings in the original code. I also fix the test case that is associated with this method. I Ran tests locally and everything seems fine from my side. Please let me know if anything needs to be improved. Thanks!

2023-04-05 07:52 UTC, tfranzel requested changes
You got a valid point there but it is only half of the truth. `3.0.0` changed their config mangagement https://github.com/iMerica/dj-rest-auth/pull/477 this was correct prior, and your fix would break people using `pre-3.0.0`.

please adapt the pr to check for the package version and then get the setting from the appropriate location.

2023-04-06 02:40 UTC, nixsiow commented
> You got a valid point there but it is only half of the truth. `3.0.0` changed their config mangagement [iMerica/dj-rest-auth#477](https://github.com/iMerica/dj-rest-auth/pull/477) this was correct prior, and your fix would break people using `pre-3.0.0`.
> 
> please adapt the pr to check for the package version and then get the setting from the appropriate location.

Hi there, thanks for your feedback! I amend my commit to check the version in the code. Please let me know if this is adequate or not. This is actually my first time contributing to open source, so please let me know if anything I can improve. Thanks again!

2023-04-15 12:26 UTC, nixsiow commented on drf_spectacular/contrib/rest_auth.py
> +
Ah… Much more elegant than my solution. Sorry, I should have noticed it earlier, it's literally on the same file! Thanks for fixing this! :D

2023-04-15 12:37 UTC, merged

2023-04-15 12:38 UTC, tfranzel commented on drf_spectacular/contrib/rest_auth.py
> +
No problem, I totally forgot about it too. thanks again for the PR.